Repository jovotech/jovo-framework, pull requests merged in 2019-03, with the labels that each got.

#415 🐛 Fixes: JovoError doesn't print module
  jovo-core/src/errors/JovoError.ts
Labels: tag: bug fix

#414 ♻️ GoogleSheetsCMS integration should reject JovoError instead of string
  jovo-integrations/jovo-cms-googlesheets/src/DefaultSheet.ts
Labels: tag: bug fix

#413 ✨ Adds dialogflow slot filling example
  examples/02_googleassistant/slot-filling/models/en-US.json
  examples/02_googleassistant/slot-filling/package.json
  examples/02_googleassistant/slot-filling/src/app.js
  examples/02_googleassistant/slot-filling/src/config.js
  examples/02_googleassistant/slot-filling/src/index.js
Labels: tag: new feature

#428 :sparkles: CMS-Caching, Platform-Specific Responses, I18Next Tests
  examples/google-sheets-cms/src/app.js
  examples/google-sheets-cms/src/config.js
  examples/i18n/src/i18n/en-US.json
  jovo-integrations/jovo-cms-googlesheets/src/DefaultSheet.ts
  jovo-integrations/jovo-cms-googlesheets/src/GoogleSheetsCMS.ts
  jovo-integrations/jovo-cms-googlesheets/src/ResponsesSheet.ts
  jovo-integrations/jovo-cms-i18next/src/I18Next.ts
  jovo-integrations/jovo-cms-i18next/test/dummy.test.ts
  jovo-integrations/jovo-cms-i18next/test/i18n/en-US.json
  jovo-integrations/jovo-cms-i18next/test/i18next.test.ts
  jovo-integrations/jovo-cms-i18next/tsconfig.json
  jovo-integrations/jovo-cms-i18next/tslint.json
  jovo-integrations/jovo-db-mongodb/src/MongoDb.ts
  jovo-integrations/jovo-platform-alexa/test/FrameworkBase.test.ts
  jovo-integrations/jovo-platform-alexa/test/modules/I18Next.test.ts
  jovo-integrations/jovo-platform-googleassistant/test/I18Next.test.ts
  package-lock.json
  package.json
Labels: tag: bug fix, tag: enhancement, tag: new feature
